name: Release Go Binaries

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: ["386", amd64, arm, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm
            goos: darwin
          - goarch: arm
            goos: windows
          - goarch: arm64
            goos: windows

    steps:
      - uses: actions/checkout@v4

      - uses: wangyoucao577/go-release-action@v1
        with:
          binary_name: "web-validator"
          asset_name: "web-validator-${{ matrix.goos }}-${{ matrix.goarch }}"
          extra_files: LICENSE README.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
          md5sum: false
          overwrite: true
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          pre_command: export GO386=softfloat CGO_ENABLED=0
          ldflags: -s -w -X "main.appVersion=${{ github.ref_name }}"
